### ISSUE TITLE
Chromecast and miracast-screenshare doesnt work

### ISSUE THREAD

**Issue by horvalos** [Suicide-Squirrel/issues_pie#18]
miracast-screen share doesnt work unable to find devices (smart tv)

Logcat provided
[logcat[1].txt](https://github.com/Suicide-Squirrel/issues_pie/files/3248992/logcat.1.txt)

**Comment by steadfasterX** [comment]
https://forum.xda-developers.com/g4/development/rom-lineageos-16-0-t3929082/post79677482

**Comment by mikeb2k** [comment]
You will need to add QCOMs WFD implementation since Miracast was killed in pie. See example:
https://review.lineageos.org/c/LineageOS/android_device_motorola_nash/+/250104

**Comment by steadfasterX** [comment]
https://gitlab.com/HardStyl3r/proprietary_vendor_lge/commit/ee0d8d25271bce827d9112ef52943a7dac616316

and

`    <bool name="config_enableWifiDisplay">true</bool>`

EDIT: The above does not work.

**Comment by rundumdieuhr** [comment]
> https://gitlab.com/HardStyl3r/proprietary_vendor_lge/commit/ee0d8d25271bce827d9112ef52943a7dac616316
> 
> and
> 
> ` <bool name="config_enableWifiDisplay">true</bool>`

Would love to see that implementation in LOS 16.0 and 15.1. :)

**Comment by steadfasterX** [comment]
We need p2p back first which might not be possible in LOS 16

**Comment by rundumdieuhr** [comment]
> We need p2p back first which might not be possible in LOS 16

Is it in LOS 15.1? https://github.com/Suicide-Squirrel/issues_oreo/issues/7

**Comment by steadfasterX** [comment]
> > We need p2p back first which might not be possible in LOS 16
> 
> Is it in LOS 15.1? [Suicide-Squirrel/issues_oreo#7](https://github.com/Suicide-Squirrel/issues_oreo/issues/7)

15.1 and 16 are not comparable when it comes to this.
I won't do any more work on 15.1 other then building new approx once a month. If I can fix a bug I do so as well but no focus on that anymore.

back to 16.0:

Unfortunately this approach [here](https://github.com/Suicide-Squirrel/issues_pie/issues/18#issuecomment-517660228) does not work .

Untested: https://github.com/TheMuppets/proprietary_vendor_lge/commit/801361358e5507af742527ecf82330b5e3cd9cbe

**Comment by gioyann** [comment]
Chromecast working perfectly on septembere 16 release.

**Comment by steadfasterX** [comment]
> Chromecast working perfectly on septembere 16 release.

LOS?

**Comment by gioyann** [comment]
> > Chromecast working perfectly on septembere 16 release.
> 
> LOS?

Your LOS 16 !

**Comment by steadfasterX** [comment]
might be related to :

https://review.lineageos.org/q/topic:%22pie-aosp-wfd%22+(status:open%20OR%20status:merged)

@thsachs can you confirm it works for you on my LOS build from 16th of Sep?

**Comment by rundumdieuhr** [comment]
> @thsachs can you confirm it works for you on my LOS build from 16th of Sep?

I clean installed your latest Nov 5 LOS 16 build. Thanks for the lots of improvement! 
(Background for full wipe and clean install: I had stayed on LOS 15.1 before. Plus, gapps cloud sync would not work for me on Sep 16 build which probably was due to incompatible gapps package on my side. So I directly went for the newest version which configures properly.)

Anyway, I just tried Google Cast from YouTube app: "Streaming to nearby device" -> "Establishing Connection" -> using microphone "Ok, connect" -> "Connecting..." circles -> "Connection could not be automatically established". :/

Edit – N.B.: I do not have a Chromecast stick, so unfortunately I can't check that one. Instead, I tried with another LG smartphone, my LG miracast TV and two Fire TV Sticks nearby. At first it wasn't clear to me that Chromecast might use a proprietary protocol, so sorry for confusing that with Miracast.

Checking Miracast. Status bar options -> Streaming ("Streamen"). Dialogue "Searching devices..." pops up and circles and circles ("Bildschirm auf Gerät übertragen"). Three screenshare devices ready but none recognized. Click on Settings yields "No nearby device found". So, Miracast appears unchanged to me. Ran out of time, so might provide a fresh Pie log later.

@gioyann what did I do differently from you?

**Comment by gioyann** [comment]
> > @thsachs
> 
> @gioyann what did I do differently from you?

I have an old chromecast, the HW's version may be the point. Anyway, what I do is just cast from youtube or Netflix simply using the dedicated "cast button" on those apps. That's all :o
