### ISSUE TITLE
Calls not working on h815

### ISSUE THREAD

**Issue by serenita** [Suicide-Squirrel/issues_pie#59]
Hi,
I'm on an LG G4 international (h815) with /e/OS 0.18-20210815130098 (the OFFICIAL build) installed. The issue also appeared on the earlier /e/OS 0.17 and on the CUSTOM build. The bootloader is unlocked the official way.

I cannot make calls nor receive them. Mobile data works fine and SMS too. If someone called, though, I can see afterwards that I have a missed call. But I don't see the incoming call when it is actually made. If I try to call a number, it doesn't do the ringing sound on my phone but it just says it would call. Then, after some seconds, it just ends the call without any error message. Maybe it's worth mentioning that the problem did not arise directly after an update or flash. Rather, first, receiving calls stopped working, then calling. So it might well be a hardware-related issue but I wanted to report it anyway.

My SIM card works in other phones so it shouldn't be the problem. I also tried another dialer app but that doesn't change anything.

Here's a log of trying to call:
https://pastebin.com/kGUDvgAu

Related: #45 

I would appreciate help!
Cheers

**Comment by steadfasterX** [comment]
Weird issue tbh. It either works or not especially on official unlocked devices this issue makes no sense and regardless of the unlock this has never been reported by anyone. The issue you linked is a complete different thing.

do you have flashed the 20p bootloader zip ? If not or unsure i would recommend doing so first.

The way you describe can lead to a damaged internal storage though. The next thing after flashing the 20p bootloader stack would be a FORMAT of userdata in the recovery. Obviously you should backup before as everything(!) will be deleted then. Sometimes the filesystem get damaged bc of other things then defective hardware - this would be fixed after the format. When there is a hardware issue the filesystem will get corrupted again sooner or later though. If that is the case can be investigated in recovery by using filesystem checks (adb shell at best or using the recovery UI).

Last but not least: flash stock (h815 - 20p). Try call/receive call there for a while. When you're certain it keeps working go back to a custom ROM first. Often enough strange issues like these can be fixed by flashing stock.

 If the problem persists when coming back from stock: share the boot logs (see faq).

**Comment by serenita** [comment]
Thanks for your answer!

Sorry, I forgot to mention. I already flashed your 20p bootloader ZIP but it didn't change anything. Formatting data didn't help either. About the filesystems I'm not sure. When I first bootet into TWRP there seemed to be a problem on /system. I recovered it and now it's gone but the situation is still the same. So I don't think it had something to do with the issue.

Can you maybe help me out with flashing the stock ROM? I already tried to but I couldn't make it work. First of all, I'm (even after some internet research) really unsure what are trustworthy places to download stock ROM since there doesn't seem to be an official LG website to download them. Second, I downloaded one anyway but then had the impression it is only flashable with the LG flash tool which is only for Windows but I couldn't get it running. Is there a way to flash using a Linux computer? I saw that on your server there are seperate images for the partitions in the `stock/.../extracted` directory. Should I use those? And if yes, which ones of them exactly?

**Comment by steadfasterX** [comment]
https://leech.binbash.rocks:8008/stock/LG/h815/20p/

h815_20p_ARB0_0314.kdz

Use LGup to flash that kdz

**Comment by serenita** [comment]
Thanks. Nevertheless, I'm close to giving up now. I eventually managed to get LGUP running on Windows (I don't see how it can run on Linux). But after flashing the .kdz file my device is stuck bootlooping. It also seems to me I cannot boot TWRP anymore (is this how it is supposed to be?). So effectively it seems I cannot do anything anymore.

**Comment by steadfasterX** [comment]
Don't give up so quickly ;)
Just boot to fastboot and use

fastboot format userdata

And try again. Yes TWRP is gone after flashing stock so you need to flash TWRP in fastboot and ensure you directly boot into TWRP jnstead of android (otherwise when android boots TWRP gets overwritten and you need to flash it again )

**Comment by serenita** [comment]
I cannot access the fastboot mode. The only real instructions on how to get to it that I found are in
https://forum.xda-developers.com/t/unlock-unofficial-g4-unlock-any-lg-g4-device-with-usu.3760451/
but my device is not UsUd. I tried it anyway but it didn't work. Some sources on the internet also seem to confuse download mode with fastboot mode. How can I get to fastboot mode?

**Comment by steadfasterX** [comment]
> I cannot access the fastboot mode. The only real instructions on how to get to it that I found are in
> https://forum.xda-developers.com/t/unlock-unofficial-g4-unlock-any-lg-g4-device-with-usu.3760451/
> but my device is not UsUd. I tried it anyway but it didn't work. Some sources on the internet also seem to confuse download mode with fastboot mode. How can I get to fastboot mode?

Try that one (can't test it atm):
`With the device powered off, hold Volume Up + Power.`
This is mentioned in the LOS wiki page for the h815 so i hope its the correct one

**Comment by serenita** [comment]
Thanks for the hint! Unfortunately it doesn't work for me. When I do Volume Up + Power while the phone is charging I get to download mode. Otherwise nothing happens. But download mode is not fastboot mode right? At least fastboot does not see my phone when it's in download mode.

**Comment by steadfasterX** [comment]
well yea I can confirm that no matter what I try I cannot boot into fastboot anymore with any key combo. you are right download mode is not fastboot mode. you can try flashing TWRP with SALT though. If that works or not depends on the LAF protocol version but give it a try. start SALT from the CLI as mentioned [here](https://forum.xda-developers.com/t/tool-locked-unlocked-salt-the-lg-up-revolution-begins.3717864/post-84581031).

then:
1. backup -> custom
2. click "deselect all"
3. select just "aboot"
4. choose a target folder and let it backup
5. in that same folder put in the latest TWRP preview and rename it to "recovery.img"
6. in SALT: click "Flash (folder)" and select the same folder again
7. again "Deselect All" and select just "recovery.img"
8. let it flash
9. open advanced menu -> debug log -> click upload button -> share link

**Comment by serenita** [comment]
I tried it but it seems my device does not support that kind of flashing: https://hastebin.com/finapecizi

**Comment by steadfasterX** [comment]
yea correct, it would work on Lollipop or my LAF version but that is not possible to flash without fastboot or twrp either. well it would be possible when using QFIL but well.. that requires some preparement first etc. dunno if thats worth it for you.
have you tried flashing stock and selecting refurbish? if not try that one (will delete the whole device)

**Comment by serenita** [comment]
Thanks a lot! Flashing in refurbish mode really did work. Now I have a working stock ROM and I can also call again.

When I had the time to test /e/ again, I'll tell you.

**Comment by steadfasterX** [comment]
perfect. re-open that issue if that occurs again then :)

**Comment by natschil** [comment]
I had the same issue, but it seems to work now after switching temporarily to prefer 3G networks (as opposed to LTE) and back again.
