### ISSUE TITLE
Updating issues with Los16 and Twrp 3.6 - h815 usu unlocked and encrypted

### ISSUE THREAD

**Issue by LifelessMuffin** [Suicide-Squirrel/issues_pie#60]
Hi folks, recently I updated my Los16-20210608 and Twrp version (I don't remember which one) to Los16-20211122 and Twrp 3.6.0_9-0. But something went wrong and of course I didn't make a backup :100: :1st_place_medal: 
Basically my data partition has been encrypted with the previous Los version when I first installed it. Then after updating to the new version, after inserting my decryption pin when asked at the system boot, the phone goes into a bootloop where the Lineage logo is repeated infinitely. 
Now the thing is that Twrp is not able to decrypt the data partition, it just kill the process because "took too long" as it says. 
I would just try to recorver the data, I tried this method but seems not working for this setup
[https://android.stackexchange.com/questions/125121/mount-android-encrypted-data-partition-on-pc](url) 

![asd](https://user-images.githubusercontent.com/58374136/144764350-4d4df496-feeb-47c5-b6e2-c7c118098c8a.png)

Any solution? I would like to copy the encrypted data partiton on my ubuntu and try to decrypt it 
Thank you in advance

**Comment by steadfasterX** [comment]
1. decrypting Android 9 / Pie / 16.0 in TWRP is not supported on the G4 and (due to lack of time) might never be.
1. TWRP errors always requires the recovery.log (just a hint, I do not need it for that particular issue)
1. my LOS builds are made with [hardware encryption](https://github.com/LGgFour/android_device_lge_g4-common/blob/eos-pie/BoardConfigCommon.mk#L118) support which means: you cannot decrypt other then on the device itself. so TWRP. see 1.
